### ISSUE TITLE
Fatal error: Class 'tubalmartin\CssMin\Minifier' not found

### ISSUE THREAD

**Issue by claire-ee** [nathancox/silverstripe-minify#15]
On a SilverStripe 3.1 site I have installed the plugin, run dev/build, set the environment to LIVE and set the combine_files to a min.css file.

On page load get the following error

    Fatal error: Class 'tubalmartin\CssMin\Minifier' not found in /var/www/sites/cto/web/minify/thirdparty/minify/lib/Minify/CSSmin.php on line 70

**Comment by nathancox** [comment]
Did you install it using composer?  tubalmartin/cssmin is added as a composer dependency.  If you're not using composer you might be able to download it manually from https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port and put it in a vendor folder in the site root or something like that.

**Comment by claire-ee** [comment]
ok, thank you
